Create Book and label classes
duskotmane/ruby-capstone pull request #38
Opened 2023-08-08 17:09 UTC by otmaneechchafyky

# Features ⭐ 🌟 ⭐ 

- [ ] Created a `Book` class in a separate .rb file.
- [ ] Created a `Label` class with an association to the Item class (in a separate .rb file).
- [ ] Made all `Book` class & `Label` class properties visible in the diagram should be defined and set up in the constructor method.
- [ ] Implemented `add_item` method in the Label class
- [ ] Overrided `can_be_archived?()` in the Book class
- [ ] Added unit tests for all implemented methods.
- [ ]  The following options are available:
        -  List all books
        - List all labels (e.g 'Gift', 'New')
        - Add a book
- [ ] Preserve books and labels data in ` json` files
- [ ] Create `books table` (add all properties and associations from the parent Item class as table columns) in ` schema.sql`  file
- [ ] Create `labels table` in ` schema.sql`  file.

2023-08-08 21:13 UTC, luigirazum requested changes
Hi @otmaneechchafyky <br>Good job so far! <br>👏👏👏 
---
However, there are some issues that you still need to work on to go to the next project, but you're almost there!

Status: ♻️ Changes Required
===
![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉
- No Linters errors ✔️
- Good job organizing classes files into one folder 👏 ✔️
- The code is understandable as you read it ✔️

 ## Required Changes ♻️
- [ ] **_Please 👀 Check the comments on the code_**
- [ ] I would like to suggest you to keep the logic that is in the requirements.
    ![image](https://github.com/otmaneechchafyky/ruby-capstone/assets/67355479/b8c6e804-7c0c-4356-8023-0f0a0d6acd14)
  - Let's try to avoid changing the logic keeping the `OR` from the requirements instead of `AND`.
    - To get a `true` value from an `AND` operation, both expressions have to be `true`.
    - To get a `true` value from an `OR` operation, just one of the expressions needs to be `true`.
  - Requirements say that `can_be_archived?` method:
    - should return true if parent's method returns true OR if cover_state equals to "bad"
    - otherwise, it should return false
- [ ] Regarding to `Label` class tests
    ![image](https://github.com/otmaneechchafyky/ruby-capstone/assets/67355479/4ffc87dc-94a1-459e-a421-c6de25b627f1)
  - I would like to suggest you adding the tests to verify:
    - That `Label` constructor receives an Item instance. You can use the `be_an_instance_of` matcher.
    - That the Item received is added in the Label 'items', perhaps using `imcludes?` could be helpful.
    - The last of the tests asks us to verify that the Label `instance` is the same `instance` that it is stored in the 'label' at Item. I think `include?` could be a better choice to do the match.

## Optional suggestions ✍️
- N/A
_Every comment with the <kbd>OPTIONAL</kbd> prefix is not crucial enough to stop the approval of this PR. <br>However, I strongly recommend you take them into account as they can make your code better._

***
Cheers and Happy Coding! 👨‍💻
---
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@luigirazum` in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. <br>You should use the same Pull Request submitted for the first review,<br>either valid or invalid unless it is requested otherwise._** 

----
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-08 21:13 UTC, luigirazum commented on .rubocop.yml
> +  Max: 10
- Regarding to the number of parameters for a method, I would like to recommend you using `*params` or a `hash` to send/receive parameters to/in a method. Just like in the `Item` class constructor(`initialize` method).
- Last but not least, it would be good to not modify the configuration files for linters, in this project that file is the `.rubocop.yml` according to the documentation of Linters Config in the [Validation section](https://github.com/microverseinc/linters-config#validation).
-----
- Could you please restore the file with the correct version?
- Doing that it would be necessary to do some refactoring on the methods that `🤖 Rubocop` shows.

2023-08-08 21:13 UTC, luigirazum commented on classes/book.rb
> +  end
- I would like to suggest you in using a `params` parameter in the `Book` constructor, just like in the `Item` class:
  ```rb
    def initialize(params)
      @id = params[:id] || rand(1..100_000)
      @genre = params[:genre]
      @author = params[:author]
      @source = params[:source]
      @label = params[:label]
      @publish_date = create_date(params[:publish_date])
      @archived = params[:archived] || false
    end
  ```
  so you can call the `Parent` class constructor using the same hash `params`
  ```rb
    super(params)
  ```
  each of the constructors will take the parameters they need.

2023-08-08 21:13 UTC, luigirazum commented on spec/book_spec.rb
> +      end
- Calling the `private` method in the tests. 😮
### This move was really nice!! 👏 

- No changes here, but it would be good to apply it in the other tests as well. Don't you think?

2023-08-08 21:13 UTC, luigirazum commented on classes/label.rb
> +  end
- For `Label` class, I would like to suggest you using the `params` hash parameter.
- In that hash it would be better to send the `id` (when we already have one). Something like the following:
  ```rb
    @id = params[:id] || rand(1..100_000)
  ```
  in case we send the `id` the label will have that `id` and in case we don't send and `id`, the value of `params[:id]` will be `nil` and then the random id will be used.

2023-08-08 21:13 UTC, luigirazum commented on spec/label_spec.rb
> +      expect(@my_label.items).to eq [@my_item]
- I would like to suggest you in using `@my_label.items.include?(@my_item)` to verify that the Item instance was added to `items` collection.
- Also, I would like to recommend you adding a test to verify that 'label' property in `@my_item` has the same `@my_label` instance.

2023-08-09 10:55 UTC, otmaneechchafyky commented on spec/book_spec.rb
> +      end
Thank you

2023-08-09 10:56 UTC, otmaneechchafyky commented on classes/label.rb
> +  end
You are totally right, I'll modify it.

2023-08-09 12:21 UTC, duskotmane commented on spec/label_spec.rb
> +      expect(@my_label.items).to eq [@my_item]
I did modified the code as you suggested @luigirazum

2023-08-09 14:21 UTC, luigirazum approved these changes
STATUS: 🟢 APPROVED!!!  🎉 🎉 🎉
===
Hi @otmaneechchafyky, 🙋‍♂️ I'm Luis and I'll be your code reviewer. 
---
### Great job !!! 👏 👏 👏 
Good work on making the changes requested in the previous review.
Your project is **complete!** now.
There is nothing else to say other than...

It's time to merge it :shipit:
---
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:
===
## To Highlight 🎉
- No Linters errors ✔️
- The App works as expected ✅
- Well done organizing the classes in a folder ✅
- Good commit messages ✅

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions ✍️
- There are some of 👀 in the comments, if you have a chance, please take a look at them.
> _Every comment with the <kbd>OPTIONAL</kbd> prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

***
Cheers and Happy Coding! 👨‍💻
---
Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me `@luigirazum` in your question so I can receive the notification, you can also reach me out on Slack using the same tag as well.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._** 

----
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-09 14:21 UTC, luigirazum commented on classes/book.rb
>    end
👏 Nice nice!!! 🎉 
- How does this method look now? Better, right?
- How about the total lines? Less, right?

2023-08-09 14:21 UTC, luigirazum commented on classes/label.rb
> +    @color = 'green'
**👀 OPTIONAL**
I would like to suggest use the default value 'green' to be in the `def initialize` line
```rb
  def initialize(title, color = 'green')
    ...
    @color = color
    ...
  end
```
If you send the color parameter, the label would be set to that color, if not, the label will be set to 'green'.
_The requirements don't say anything about a default value for the color_

2023-08-09 14:21 UTC, luigirazum commented on classes/app.rb
> +    cover_state = gets.chomp
**👀 OPTIONAL**
When asking for the 'Book' information, don't you think it would be better to give the user a small hint about what the app is asking for?
- For instance when is asking for a 'Date', perhaps we could show the required date format (YYYY/MM/DD).
- And when we are creating a 'Book' it can be 'archived' immediately?

2023-08-09 14:21 UTC, luigirazum commented on classes/app.rb
> +    end
👏 Nice, nice!! 🎉 
Of course we need to verify if we have something to list.

2023-08-09 17:26 UTC, otmaneechchafyky commented on classes/book.rb
>    end
Yes exactly, less code, better code.

2023-08-09 17:26 UTC, otmaneechchafyky commented on classes/book.rb
>    end
Yes exactly, less code, better code.

2023-08-09 17:52 UTC, otmaneechchafyky commented on classes/app.rb
> +    cover_state = gets.chomp
Okay then I will do it

2023-08-09 17:53 UTC, otmaneechchafyky commented on classes/app.rb
> +    end
Yes we have color as well we may show it.

2023-08-10 13:58 UTC, luigirazum approved these changes
STATUS: 🟢 APPROVED!!!  🎉 🎉 🎉
===
Hi @otmaneechchafyky, 🙋‍♂️ I'm Luis and I'll be your code reviewer. 
---
Good work on making the optional suggested changes from the previous review.
### Great job !!! 👏 👏 👏 
Your project is **complete!**

Now you can merge this branch and move on 🥇 
---
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:
===
## To Highlight 🎉
- No Linters errors ✔️
- You can create Books ✅
- You can create Labels ✅
- The App works as expected 🤯 ✔️ 
- Good commit messages.

![giphy](https://github.com/otmaneechchafyky/ruby-capstone/assets/67355479/1aefe373-99d0-447a-a9ee-f6bfdfc7fd7b)

## Optional suggestions ✍️
- N/A
> _Every comment with the <kbd>OPTIONAL</kbd> prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

***
Happy Coding! 👨‍💻 and Good Luck 🍀 with the coming ones 🤞
---
Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me `@luigirazum` in your question so I can receive the notification, you can also reach me out on Slack using the same tag as well.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._** 

----
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-12 10:11 UTC, binodbhusal approved these changes
STATUS: 🟢 APPROVED!!! 🎉 🎉 🎉
Hi @otmaneechchafyky  , 🙋‍♂️ I'm Binod your code reviewer.
Good work on making effort on this project !!

Great job !!! 👏 👏 👏
Your project is complete!

Now you can merge this branch and move on 🥇
Congratulations! 🎉 🎉 🎉 🍾 🍾 🍾
To Highlight 🎉
No Linters errors ✔️
Can create tables✔️
Provides a foundation for representing the structure and associations of your classes in a relational database✔️
The app works as expected ✅
Good commit messages. 👍


Optional suggestions ✍️

- Add a NOT NULL constraint to the 'title' column of the 'labels' table. This ensures that every label must have a title, which is important for data integrity.

- Consider adding default values for certain columns, such as 'archived' in the 'items' table, if applicable.

Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

2023-08-12 12:09 UTC, merged